### ISSUE TITLE
Off topic: PyPI name `rip` 

### ISSUE THREAD

**Issue by wolfv** [dschaller/forkers#10]
Hi @dschaller, 

sorry for abusing this way of getting in contact with you. We've just released https://github.com/prefix-dev/rip which is a fast pip implementation in Rust and would love to take over the PyPI (https://pypi.org/project/rip/) name of which you are an admin. I would be delighted if you could get in touch via LinkedIn or Email (is on my Github profile).

Would be amazing!

Have a nice day, 
Wolf

**Comment by dschaller** [comment]
:D no worries - I replied over linkedin
